name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  BUILD_DIR: ${{ github.workspace}}/vsbuild

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Check CMake version
      run: cmake --version

    - name: Configure CMake
      run: |
        mkdir "${{ env.BUILD_DIR }}"
        cd "${{ env.BUILD_DIR }}"
        cmake ..
      shell: cmd

    - name: Build
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        cmake --build . --config Release
      shell: cmd

    - name: Test
      working-directory: ${{ env.BUILD_DIR }}
      run: ctest -C Release
      shell: cmd
